pull_request_rules:
  - name: Test passed for code changed
    conditions:
      - base=master
      - "status-success=Java CI with Maven / Build with Maven"
    actions:
      label:
        add:
          - ci-passed

  - name: Remove ci-passed when code check failed
    conditions:
      - base=master
      - "check-failure=Java CI with Maven / Build with Maven"
    actions:
      label:
        remove:
          - ci-passed
